### ISSUE TITLE
Notebook  "Calculation_of_local_lattice_rotation"

### ISSUE THREAD

**Issue by L-Fr** [AndreasLeitherer/ai4stem#1]
Dear Andreas,
I have started to try the notebook. However, the module called "ai4stem.utils.utils_spm" could not be found. It is alsso not in the folder "ai4stem/ai4stem/utils". Did you not upload it or do you have any other idea for solving this issue?

Best regards from MPIE,
Lena

**Comment by AndreasLeitherer** [comment]
Hi Lena,

thank you for letting me know! 

I renamed this and forgot to correct it in this particular notebook - I have updated it now. Basically 'ai4stem.utils.utils_spm' moved to 'ai4stem.utils.utils_prediction' (see the latest commit).

Best regards from FHI/Humboldt,
Andreas

**Comment by L-Fr** [comment]
Thanks, perfect. It is working now! :)

**Comment by AndreasLeitherer** [comment]
Great!
